image: python:3.12-slim

variables:
  DEBIAN_FRONTEND: noninteractive
  QT_QPA_PLATFORM: offscreen
  PYTHONPATH: $CI_PROJECT_DIR

stages:
  - test

before_script:
  - apt-get update -qq
  - apt-get install -y -qq git make wget
  # Install newer Pandoc from GitHub releases
  - wget https://github.com/jgm/pandoc/releases/download/3.1.9/pandoc-3.1.9-1-amd64.deb
  - dpkg -i pandoc-3.1.9-1-amd64.deb
  - apt-get install -y -qq qt5-qmake qtbase5-dev qtwebengine5-dev
  - apt-get install -y -qq xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0
  - apt-get install -y -qq libqt5gui5 libqt5widgets5 libqt5webenginewidgets5
  - git submodule update --init --recursive
  - pip install --upgrade pip
  - pip install -r requirements.txt

test:
  stage: test
  script:
    # Set up virtual display for Qt GUI tests
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - export DISPLAY=:99.0
    - make all_tests
    # Coverage report is available as GitLab artifact
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.xml
    expire_in: 1 week
