language: python
python:
  - "3.6"
install: "pip install -r requirements.txt"
script: make all_tests
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb
after_success:
  - coveralls
