language: python
python:
  - "3.6"
install: "pip install -r requirements.txt"
script: make all_tests
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-1-amd64.deb
  - sudo dpkg -i pandoc-2.5-1-amd64.deb
after_success:
  - coveralls
