language: python
python:
  - "3.5"
install: "pip install -r requirements.txt"
script: make all_tests
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/1.17.0.1/pandoc-1.17.0.1-1-amd64.deb
  - sudo dpkg -i pandoc-1.17.0.1-1-amd64.deb
