name: Build AppImage Container

on:
  push:
    paths:
      - '.github/Dockerfile.appimage'
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: .github/Dockerfile.appimage
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/appimage-builder:latest
          ghcr.io/${{ github.repository }}/appimage-builder:${{ github.sha }}